### ISSUE TITLE
Compiler fails - In system(cmd) : 'make' not found

### ISSUE THREAD

**Issue by seanglacoursiere** [matiasandina/wholebrain_install#1]
Hi Matias Andina, 

 I have been following your manual for installing wholebrain for Windows 10. So far it appears everything is going well but once I attempt to check the compiler, it fails to compile C code. 

> path_variables <- unlist(strsplit(Sys.getenv("PATH"), ";"))
> grep("CMake", path_variables, value=TRUE)

[1] "C:\\Program Files\\CMake\\bin" "C:\\CMake\\bin"               
> pkgbuild::check_compiler(debug = TRUE)

Trying to compile a simple C file
Running "C:/R/bin/x64/Rcmd.exe" SHLIB foo.c
Warning message:
In system(cmd) : 'make' not found
Error: Failed to compile C

Is this because I do not have the proper path set for R? It does not seem to be running Rtools.

**Comment by piv1k** [comment]
I have the same trouble! Please, help me. I can not solve the problem

R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Windows 10 x64

**Comment by matiasandina** [comment]
Hello,
I have not tried this with R 4.1
That release is somewhat new, I would not recommend using that. If you
cannot figure it out, I would try to downgrade R to a previous version, say
3.6
That is more likely to be compatible with things like Rtools.
That being said, I believe not finding the compiler might be due to failing
to add it to path or some other make installation problem and not R itself
